// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npstnyiraoowffbghita.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wc3RueWlyYW9vd2ZmYmdoaXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODA1NzYsImV4cCI6MjA3MzE1NjU3Nn0.itGeRdH8TRIbiXzl-wJAM7MpItwWFRklP_TgYu7EeeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
